# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"

[main.params]
icon = "home"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/jwendl"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "X"
url = "https://x.com"

[social.params]
icon = "brand-twitter"
