title: "Jwendl.NET | All about Code"
author: "Justin Wendlandt"
description: "Justin Wendlandt's blog about software development on Microsoft Azure"
more: "read more »"
url: "https://www.jwendl.net"
# baseurl: "/contrast" # comment out if in root directory

comments:
  disqus: "jwendl-net-all-about-code"
#  isso: "comments.mysite.org"

style:
  body: 'white'
  margin: 0%
  padding: 30%
  nav: "#222"
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  uppercase: true

# see http://fontawesome.io/icons/#brand for all possible icons
# notice: squared icons only work if supported by font-awesome

links:
  - github: {url: "https://github.com/jwendl/", square: true}
  - reddit: {url: "https://www.reddit.com/user/jwendl/", square: true}
  - twitter: {url: "https://twitter.com/jwendl/", square: true}
  - facebook: {url: "https://www.facebook.com/jwendl", square: true}
  - google-plus: {url: "https://plus.google.com/+jwendl", square: true}
  - youtube: {url: "https://www.youtube.com/user/jwendl", square: true}
  - steam: {url: "http://steamcommunity.com/id/jwendl/", square: true}

paginate: 10
excerpt_separator: "&shy;" # excerpt ends after two blank lines
permalink: pretty
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}, {scope: {path: "images"}, values: {image: true}}, {scope: {path: "lib"}, values: {script: true}}]
gems: [jekyll-feed, jekyll-paginate, jekyll-gist] # include feed plugin (supported by gh-pages)
